import {writable,readable} from "svelte/store";
export const keylist=readable(['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal', 'Backspace', 'Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash', 'CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter', 'ShiftLeft', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ShiftRight', 'ControlLeft', 'None' ,'AltLeft', 'Space', 'AltRight','None' ,'ContextMenu', 'ControlRight']);
export const keysize=readable([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1.5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.5, 1.75, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2.25, 2.25, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2.75, 1.25, 1.25, 1.25, 6.25, 1.25, 1.25, 1.25, 1.25]);
export const keyscount=readable([14,28,41,53,61]);
export const NonCap=readable(['ऽ', '१', '२', '३', '४', '५', '६', '७', '८', '९', '०', '-', '',"Back","Tab", 'ट', 'ौ', 'े', 'र', 'त', 'य', 'ु', 'ि', 'ो', 'प', 'इ', 'ए', 'ॐ',"Caps", 'ा', 'स', 'द', 'उ', 'ग', 'ह', 'ज', 'क', 'ल', ';', "'","Enter","Shift", 'ष', 'ड', 'छ', 'व', 'ब', 'न', 'म', ',' ,'।', '्',"Shift","Ctrl","WN","Alt"," ","Alt","FN","Ctx","Ctrl"]);
export const Cap=readable(['़', '!', '@', '#', '$', '%', '^', '&', '*', '', '॰', '॒', '',"None","None", 'ठ', 'औ', 'ै', 'ृ', 'थ', 'ञ', 'ू', 'ी', 'ओ', 'फ', 'ई', 'ऐ', 'ः',"None", 'आ', 'श', 'ध', 'ऊ', 'घ', 'अ', 'झ', 'ख', 'ळ', ':', '"',"None","None", 'ऋ', 'ढ', 'च', 'ँ', 'भ', 'ण', 'ं', 'ङ', '॥', '?',"None","None","None","None","None","None","None","None","None"]);
let length=0;
const unsubscribe=keylist.subscribe((value)=>length=value.length);
export const speed=writable(Array(length).fill([[],[]]));
